# Generated by Django 3.2.23 on 2023-12-09 13:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='test',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
