# Generated by Django 3.2.23 on 2023-12-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_comment_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='test',
        ),
    ]
